version: "3.9"
services:
    web:
        build: .
        ports:
            - "5000:5000"
            - "5001:5001"
            - "8000:8000"
        depends_on:
            - mssql
    mssql:
        build: carrentaldatabase
        ports:
            - "1433:1433"